version: '1.0'
networks:
  dockernet:
    external: true
services:
  app:
    container_name: app
    build: .
    ports:
      - ${PORT}:${PORT}
      - 9222:9222
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    networks:
      - dockernet

  db:
    container_name: postgres
    image: postgres
    ports:
      - 5433:${POSTGRES_DB_PORT}
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    networks:
      - dockernet


volumes:
  data: {}
